/* =====================================================================
   app.js — 화면 전체가 함께 쓰는 "바뀌는 값" 한 곳에 모음
   ---------------------------------------------------------------------
   모든 모듈이 import { App } from '@app/core/app.js' 로 같은 객체를 씁니다.
   예: App.raid (지금 보고 있는 공략대 레이드), App.events (그 공략대 기록),
       App.selected (결과 입력에서 고른 공략대원), App.authUser (로그인한 계정)
   값을 바꾸면 render() 를 불러 화면에 반영합니다.
   실제 초기값은 각 파일의 init() 에서 정해집니다 (아래는 목록과 설명용).
   ===================================================================== */
export const App = {
  db: undefined,
  local: undefined,
  readOnly: undefined,
  online: undefined,
  history: undefined,
  histTab: undefined,
  openHist: undefined,
  raid: undefined,
  events: undefined,
  unsubEvents: undefined,
  subRaidId: undefined,
  ladderSnap: undefined,
  collector: undefined,
  unsubLadder: undefined,
  raids: undefined,
  allEvents: undefined,
  allLadder: undefined,
  curRid: undefined,
  eventsReady: undefined,
  selected: undefined,
  isWin: undefined,
  diff: undefined,
  confirmArm: undefined,
  spinning: undefined,
  lastState: undefined,
  setupList: undefined,
  setupRoles: undefined,
  gearSpinning: undefined,
  seenEv: undefined,
  seenRaid: undefined,
  ovlView: undefined,
  modalMode: undefined,
  setupSrc: undefined,
  skTab: undefined,
  skDirty: undefined,
  bsDraft: undefined,
  rsDraft: undefined,
  gDraft: undefined,
  setDraft: undefined,
  setDirty: undefined,
  calcIn: undefined,
  inviteCode: undefined,
  inviteFor: undefined,
  unsubInvite: undefined,
  kickArm: undefined,
  auth: undefined,
  authUser: undefined,
  profile: undefined,
  admins: undefined,
  adminsLoaded: undefined,
  unsubProfile: undefined,
  deleteArm: undefined,
  dropArm: undefined,
  archiveTimer: undefined,
  rankTab: undefined,
  meName: undefined,
  localDB: undefined,
  legacyChecked: undefined,
};
